# Generated by Django 5.2.5 on 2026-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_add_waba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='waba_id',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp ID extraido do remoteJid', max_length=50, null=True, unique=True),
        ),
    ]
