# Generated by Django 5.2.5 on 2025-09-08 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wppmessages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
