# Generated by Django 5.2.5 on 2026-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
