# Generated by Django 5.2.5 on 2026-03-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0002_chatmessage_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('product', 'Product'), ('category', 'Category'), ('catalog', 'Catalog'), ('image', 'Image')], default='text', max_length=20),
        ),
    ]
