# Generated by Django 5.2.5 on 2026-03-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0003_add_catalog_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('product', 'Product'), ('category', 'Category'), ('catalog', 'Catalog'), ('image', 'Image'), ('audio', 'Audio')], default='text', max_length=20),
        ),
    ]
