# Generated by Django 5.2.5 on 2026-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_minimum',
            field=models.IntegerField(default=5),
        ),
    ]
